### ISSUE TITLE
failed generate sprite

### ISSUE THREAD

**Issue by ivanzhang92** [creeperyang/ysprite#2]
just install with:
`npm install -g ysprite`

folder structure:
![2016-02-16 9 38 05](https://cloud.githubusercontent.com/assets/1987882/13064811/0cbb6bc0-d491-11e5-89f0-d63b863bd837.png)

and run with:
![2016-02-16 9 38 46](https://cloud.githubusercontent.com/assets/1987882/13064816/190b4864-d491-11e5-9792-8e9cb0281c68.png)

However,it do generate a sprite image without css file,but it seems that the result is repeating.
![2016-02-16 9 40 13](https://cloud.githubusercontent.com/assets/1987882/13064845/668457ac-d491-11e5-94ef-d41fa1b5bae2.png)

i try to run `ysprite -r` in the folder sprites and it works!

**Comment by creeperyang** [comment]
The repeated part is pre generated `sprite.png`. Maybe the lib should give user a way to specify/filter images to generate sprite.

Anyway, the upcoming `v2` will resolve it.
